//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/_Scripts/UI Buttons.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIButtons : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIButtons()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UI Buttons"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""dd6befae-1b1c-46e8-9e52-2303ab0246b9"",
            ""actions"": [
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""f7f4e86e-fdf2-4f9e-8e01-86c2708bb798"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Level Select"",
                    ""type"": ""Button"",
                    ""id"": ""c3646ca8-7405-43c9-9385-5a4cc66ddb8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""1bcced32-4819-41d6-aa8a-dabba9eab920"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""3f479239-25e8-4194-8fca-2260ccd4f274"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Resume"",
                    ""type"": ""Button"",
                    ""id"": ""993b88fe-8d20-4edf-97f2-404a4fdf3031"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""d4a49668-09d9-4896-aff1-c71cfc3a3a74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d99302d6-85b5-4190-89fa-cad508443150"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Level Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40609e34-16a9-4277-95e9-59d04228f366"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""750eae80-c17c-4d4e-b458-13a83b1f6f90"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e30ae924-22e0-48f6-83ec-4070572ae0ad"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""116f651b-de74-471b-b995-5624ea16b1cc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""883fdd67-5c31-4c13-8cf0-172987358794"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level Select"",
            ""id"": ""dee5a52b-3b9d-43da-a9b5-a26eb1d58c8e"",
            ""actions"": [
                {
                    ""name"": ""Level1"",
                    ""type"": ""Button"",
                    ""id"": ""73e0dd8f-099f-46ec-b88d-3adcd34f01d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Level2"",
                    ""type"": ""Button"",
                    ""id"": ""7042c076-39ca-4576-8856-bc1f4c105aa3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Level3"",
                    ""type"": ""Button"",
                    ""id"": ""96f391aa-a899-4986-9a28-03f4c8304108"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""6d216466-38e9-437b-8967-22fdfe867624"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dd50f54d-e4e5-4c18-bdec-14b40e24bcf5"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Level1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b1d335d-8594-413c-8fc5-09b8e5ec035a"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Level2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b643141-dfe7-4778-8d31-8a422b4cdaaf"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Level3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae83f8d1-cd65-4c23-87ab-b68179536c1e"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Start = m_UI.FindAction("Start", throwIfNotFound: true);
        m_UI_LevelSelect = m_UI.FindAction("Level Select", throwIfNotFound: true);
        m_UI_Quit = m_UI.FindAction("Quit", throwIfNotFound: true);
        m_UI_Pause = m_UI.FindAction("Pause", throwIfNotFound: true);
        m_UI_Resume = m_UI.FindAction("Resume", throwIfNotFound: true);
        m_UI_MainMenu = m_UI.FindAction("MainMenu", throwIfNotFound: true);
        // Level Select
        m_LevelSelect = asset.FindActionMap("Level Select", throwIfNotFound: true);
        m_LevelSelect_Level1 = m_LevelSelect.FindAction("Level1", throwIfNotFound: true);
        m_LevelSelect_Level2 = m_LevelSelect.FindAction("Level2", throwIfNotFound: true);
        m_LevelSelect_Level3 = m_LevelSelect.FindAction("Level3", throwIfNotFound: true);
        m_LevelSelect_Close = m_LevelSelect.FindAction("Close", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Start;
    private readonly InputAction m_UI_LevelSelect;
    private readonly InputAction m_UI_Quit;
    private readonly InputAction m_UI_Pause;
    private readonly InputAction m_UI_Resume;
    private readonly InputAction m_UI_MainMenu;
    public struct UIActions
    {
        private @UIButtons m_Wrapper;
        public UIActions(@UIButtons wrapper) { m_Wrapper = wrapper; }
        public InputAction @Start => m_Wrapper.m_UI_Start;
        public InputAction @LevelSelect => m_Wrapper.m_UI_LevelSelect;
        public InputAction @Quit => m_Wrapper.m_UI_Quit;
        public InputAction @Pause => m_Wrapper.m_UI_Pause;
        public InputAction @Resume => m_Wrapper.m_UI_Resume;
        public InputAction @MainMenu => m_Wrapper.m_UI_MainMenu;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Start.started -= m_Wrapper.m_UIActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnStart;
                @LevelSelect.started -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelSelect;
                @LevelSelect.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelSelect;
                @LevelSelect.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelSelect;
                @Quit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnQuit;
                @Quit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnQuit;
                @Quit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnQuit;
                @Pause.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @Resume.started -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
                @Resume.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
                @Resume.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
                @MainMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMainMenu;
                @MainMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMainMenu;
                @MainMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMainMenu;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @LevelSelect.started += instance.OnLevelSelect;
                @LevelSelect.performed += instance.OnLevelSelect;
                @LevelSelect.canceled += instance.OnLevelSelect;
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Resume.started += instance.OnResume;
                @Resume.performed += instance.OnResume;
                @Resume.canceled += instance.OnResume;
                @MainMenu.started += instance.OnMainMenu;
                @MainMenu.performed += instance.OnMainMenu;
                @MainMenu.canceled += instance.OnMainMenu;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // Level Select
    private readonly InputActionMap m_LevelSelect;
    private ILevelSelectActions m_LevelSelectActionsCallbackInterface;
    private readonly InputAction m_LevelSelect_Level1;
    private readonly InputAction m_LevelSelect_Level2;
    private readonly InputAction m_LevelSelect_Level3;
    private readonly InputAction m_LevelSelect_Close;
    public struct LevelSelectActions
    {
        private @UIButtons m_Wrapper;
        public LevelSelectActions(@UIButtons wrapper) { m_Wrapper = wrapper; }
        public InputAction @Level1 => m_Wrapper.m_LevelSelect_Level1;
        public InputAction @Level2 => m_Wrapper.m_LevelSelect_Level2;
        public InputAction @Level3 => m_Wrapper.m_LevelSelect_Level3;
        public InputAction @Close => m_Wrapper.m_LevelSelect_Close;
        public InputActionMap Get() { return m_Wrapper.m_LevelSelect; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LevelSelectActions set) { return set.Get(); }
        public void SetCallbacks(ILevelSelectActions instance)
        {
            if (m_Wrapper.m_LevelSelectActionsCallbackInterface != null)
            {
                @Level1.started -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel1;
                @Level1.performed -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel1;
                @Level1.canceled -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel1;
                @Level2.started -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel2;
                @Level2.performed -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel2;
                @Level2.canceled -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel2;
                @Level3.started -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel3;
                @Level3.performed -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel3;
                @Level3.canceled -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnLevel3;
                @Close.started -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnClose;
                @Close.performed -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnClose;
                @Close.canceled -= m_Wrapper.m_LevelSelectActionsCallbackInterface.OnClose;
            }
            m_Wrapper.m_LevelSelectActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Level1.started += instance.OnLevel1;
                @Level1.performed += instance.OnLevel1;
                @Level1.canceled += instance.OnLevel1;
                @Level2.started += instance.OnLevel2;
                @Level2.performed += instance.OnLevel2;
                @Level2.canceled += instance.OnLevel2;
                @Level3.started += instance.OnLevel3;
                @Level3.performed += instance.OnLevel3;
                @Level3.canceled += instance.OnLevel3;
                @Close.started += instance.OnClose;
                @Close.performed += instance.OnClose;
                @Close.canceled += instance.OnClose;
            }
        }
    }
    public LevelSelectActions @LevelSelect => new LevelSelectActions(this);
    public interface IUIActions
    {
        void OnStart(InputAction.CallbackContext context);
        void OnLevelSelect(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnResume(InputAction.CallbackContext context);
        void OnMainMenu(InputAction.CallbackContext context);
    }
    public interface ILevelSelectActions
    {
        void OnLevel1(InputAction.CallbackContext context);
        void OnLevel2(InputAction.CallbackContext context);
        void OnLevel3(InputAction.CallbackContext context);
        void OnClose(InputAction.CallbackContext context);
    }
}
